name: Update Submodule

on:
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  update_submodule:
    runs-on: ubuntu-latest
    steps:
      - name: checkout repo
      - uses: actions/checkout@v2
        with:
          submodules: recursive

      - name: update submodule
        run: |
          git submodule update --remote --merge

      - name: create pull request
        id: cpr
        uses: peter-evans/create-pull-request@v3
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          commit-message: Update report
          committer: GitHub <noreply@github.com>
          author: ${{ github.actor }} <${{ github.actor }}@users.noreply.github.com>
          signoff: false
          branch: update-database-backup-submodule
          delete-branch: true
          title: 'Update database backup submodule'
          body: |
            ## Purpose

            Automated backup update

            ## Additional

            Auto-generated by [create-pull-request][1]

            [1]: https://github.com/peter-evans/create-pull-request
          labels: automated update
          draft: false
